version: '2.1'

services:
  auth:
    image: auth:v0.0.1
    build: challenge-auth
    mem_limit: 1024m
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      
  api:
    image: api:v0.0.1
    build: challenge-api
    mem_limit: 1024m
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=default

  data-collector:
    image: data_collector:v0.0.1
    build: challenge-data-collector
    mem_limit: 1024m
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=default

  data-provider:
    image: data-provider:v0.0.1
    build: challenge-data-provider
    mem_limit: 1024m
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=default
