version: '2.1'

services:   
  api:
    image: api:v0.0.1
    build: challenge-api
    mem_limit: 1024m
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  data-collector:
    image: data_collector:v0.0.1
    build: challenge-data-collector
    mem_limit: 1024m
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  data-provider:
    image: data-provider:v0.0.1
    build: challenge-data-provider
    mem_limit: 1024m
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
