version: '2.1'

services:   
  challenge-api:
    image: challenge-api:0.0.1
    build: challenge-api
    mem_limit: 1024m
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  challenge-data-collector:
    image: challenge-data_collector:0.0.1
    build: challenge-data-collector
    mem_limit: 1024m
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  challenge-data-provider:
    image: challenge-data-provider:0.0.1
    build: challenge-data-provider
    mem_limit: 1024m
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
