version: '2'

services:   
  challenge-monitor:
    image: $REGISTRY/challenge-monitor:$TAG
    ports:
      - "8090:8090"
    mem_limit: 8g

  challenge-api:
    image: $REGISTRY/challenge-api:$TAG
    ports:
      - "8091:8091"
    volumes:
      - /var/log/challenge-api:/logs
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    mem_limit: 8g 

  challenge-data-collector:
    image: $REGISTRY/challenge-data-collector:$TAG
    ports:
      - "8092:8092"
    volumes:
      - /var/log/challenge-data-collector:/logs
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    mem_limit: 16g 

  challenge-data-provider:
    image: $REGISTRY/challenge-data-provider:$TAG
    ports:
      - "8093:8093"
    volumes:
      - /var/log/challenge-data-provider:/logs
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    mem_limit: 16g 
