INSERT INTO NT_AUTHORITY (AUTHORITY_NAME) values ('ROLE_ADMIN');
INSERT INTO NT_AUTHORITY (AUTHORITY_NAME) values ('ROLE_DATA');

INSERT INTO NT_USER (USER_ID, USERNAME, PASSWORD, EMAIL, PHONE, ACTIVATED) VALUES ('admin', 'admin_name', '$2a$10$ZopyHUrwUiE1n2Y0ck.JkuHPB34PQ8U6qTHPRRg6nPYinAeOBirs.', 'admin@email...', '010-...', true);
INSERT INTO NT_USER (USER_ID, USERNAME, PASSWORD, EMAIL, PHONE, ACTIVATED) VALUES ('algorithm', 'algorithm_name', '$2a$10$ZopyHUrwUiE1n2Y0ck.JkuHPB34PQ8U6qTHPRRg6nPYinAeOBirs.', 'algorithm@email...', '010-...', true);
INSERT INTO NT_USER (USER_ID, USERNAME, PASSWORD, EMAIL, PHONE, ACTIVATED) VALUES ('simulator', 'simulator_name', '$2a$10$ZopyHUrwUiE1n2Y0ck.JkuHPB34PQ8U6qTHPRRg6nPYinAeOBirs.', 'simulator@email...', '010-...', true);

INSERT INTO NT_USER_AUTHORITY (USER_ID, AUTHORITY_NAME) values ('admin', 'ROLE_ADMIN');
INSERT INTO NT_USER_AUTHORITY (USER_ID, AUTHORITY_NAME) values ('algorithm', 'ROLE_DATA');
INSERT INTO NT_USER_AUTHORITY (USER_ID, AUTHORITY_NAME) values ('simulator', 'ROLE_DATA');