version: '2'

services:
  prometheus:
    build: .
    image: prometheus
    ports:
      - 9090:9090
    volumes:
      - prometheus:/prometheus
    mem_limit: 2048m
    restart: unless-stopped

volumes:
  prometheus:
