# set active profile
spring:
  profiles:
    active:
    - default
    
# default
profile:
  message: This is default profile.
  
server:
  port: 7001
  
logging:
  level:
    root: INFO
    web: DEBUG
