# set active profile
spring:
  profiles:
    active:
    - default
    
# default
profile:
  message: This is default profile.
  
service:
  message: Hello, Auth!
  
server:
  port: 8081
  
logging:
  level:
    root: INFO
    web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
