# test
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    username: SA
    password:
    initialization-mode: always     # never, always
    schema: classpath:database/schema-h2.sql
    data: classpath:database/data-h2.sql

  jpa:
    hibernate: 
      ddl-auto: none                # set none because default value for h2 is create-update.
      