INSERT INTO NT_CAMERA (CAMERA_ID, PASSWORD, SETTINGS_UPDATED) VALUES ('C0001', '$2a$10$ZopyHUrwUiE1n2Y0ck.JkuHPB34PQ8U6qTHPRRg6nPYinAeOBirs.', false);
INSERT INTO NT_CAMERA (CAMERA_ID, PASSWORD, SETTINGS_UPDATED) VALUES ('C0002', '$2a$10$ZopyHUrwUiE1n2Y0ck.JkuHPB34PQ8U6qTHPRRg6nPYinAeOBirs.', true);
INSERT INTO NT_CAMERA (CAMERA_ID, PASSWORD, SETTINGS_UPDATED) VALUES ('C0003', '$2a$10$ZopyHUrwUiE1n2Y0ck.JkuHPB34PQ8U6qTHPRRg6nPYinAeOBirs.', true);
