INSERT INTO NT_CAMERA (CAMERA_ID, PASSWORD, SETTINGS_UPDATED) VALUES ('C0001', '$2a$10$yDDMlDFdPj5vQnK61yPeiOM//giRQO93AeiybkRxmM/uHoS2WPfFu', false);
INSERT INTO NT_CAMERA (CAMERA_ID, PASSWORD, SETTINGS_UPDATED) VALUES ('C0002', '$2a$10$yDDMlDFdPj5vQnK61yPeiOM//giRQO93AeiybkRxmM/uHoS2WPfFu', true);
INSERT INTO NT_CAMERA (CAMERA_ID, PASSWORD, SETTINGS_UPDATED) VALUES ('C0003', '$2a$10$yDDMlDFdPj5vQnK61yPeiOM//giRQO93AeiybkRxmM/uHoS2WPfFu', true);
