apiVersion: v1
kind: Pod
metadata:
  name: docker-registry
  namespace: registry
  labels:
    app: docker-registry
spec:
  #nodeName: kube-node2 
  #nodeSelector:
    #kubernetes.io/hostname: kube-node2
  containers:
  - name: docker-registry
    image: registry:2.7.1
    ports:
    - containerPort: 5000
    volumeMounts:
    - mountPath: /var/lib/registry
      name: host-path
  volumes: 
  - name: host-path
    hostPath:
      path: /docker-registry
      type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  namespace: registry
spec:
  type: NodePort
  selector:
    app: docker-registry
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500
