apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: challenge-monitor
  template:
    metadata:
      labels:
        app: challenge-monitor
    spec:
      containers:
      - name: challenge-monitor
        image: 192.168.0.241:5000/challenge-monitor:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 512Mi
          limits:
            memory: 1Gi
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: challenge-monitor
#spec:
#  type: NodePort
#  selector:
#    app: challenge-monitor
#  ports:
#    - port: 8080
#      nodePort: 31080
#      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: challenge-monitor
spec:
  type: LoadBalancer
  selector:
    app: challenge-monitor
  ports:
    - port: 80
      targetPort: 8080
