INSERT INTO USER (ID, USER_ID, USERNAME, PASSWORD, EMAIL, ACTIVATED) VALUES (1, 'admin1', 'admin_name1', '$2a$10$ZopyHUrwUiE1n2Y0ck.JkuHPB34PQ8U6qTHPRRg6nPYinAeOBirs.', 'admin1@email...', 1);
INSERT INTO USER (ID, USER_ID, USERNAME, PASSWORD, EMAIL, ACTIVATED) VALUES (2, 'user1', 'user_name1', '$2a$10$ZopyHUrwUiE1n2Y0ck.JkuHPB34PQ8U6qTHPRRg6nPYinAeOBirs.', 'user1@email...', 1);

INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_USER');
INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_ADMIN');

INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) values ('admin1', 'ROLE_USER');
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) values ('admin1', 'ROLE_ADMIN');
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) values ('user1', 'ROLE_USER');