INSERT INTO NT_AUTHORITY (AUTHORITY_NAME) values ('ROLE_ADMIN');
INSERT INTO NT_AUTHORITY (AUTHORITY_NAME) values ('ROLE_MANAGER');
INSERT INTO NT_AUTHORITY (AUTHORITY_NAME) values ('ROLE_USER');
INSERT INTO NT_AUTHORITY (AUTHORITY_NAME) values ('ROLE_DATA');
INSERT INTO NT_AUTHORITY (AUTHORITY_NAME) values ('ROLE_CAMERA_ADMIN');
INSERT INTO NT_AUTHORITY (AUTHORITY_NAME) values ('ROLE_CAMERA');
INSERT INTO NT_AUTHORITY (AUTHORITY_NAME) values ('ROLE_AVL_CAR');
