apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-server
spec:
  accessModes:
  - ReadWriteOnce  #  must be ReadWriteOnce
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.0.241
    path: /nfs-share/prometheus/server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-server 
  namespace: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
