version: '2'

services:
  registry-web:
    image: hyper/docker-registry-web
    ports:
      - 8080:8080
    volumes:
      - ./conf/registry-web:/conf:ro
      - ./data/registry-web:/data
    restart: unless-stopped
    networks:
      - registry-net
    depends_on:
       - registry

  registry:
    image: registry
    ports:
      - 5000:5000
    volumes:
      - ./conf/registry:/etc/docker/registry:ro
      - ./data/registry:/var/lib/registry
    restart: unless-stopped
    networks:
      - registry-net

networks:
  registry-net:
#    driver: default
